## Расчетно-графическая работа 1. Выполнение операций над булевыми матрицами

In [1]:
import numpy as np

A = np.random.randint(0,2,(3,3)) # случайная булева матрица 3x3
B = np.random.randint(0,2,(3,3))

print("A")
print(A)

print("B")
print(B)

A
[[1 0 0]
 [1 1 0]
 [0 0 0]]
B
[[0 1 0]
 [0 0 1]
 [0 1 1]]


In [2]:
print("Дизъюнкция: A U B")
A_or_B = np.logical_or(A, B).astype(int)
print(A_or_B)

Дизъюнкция: A U B
[[1 1 0]
 [1 1 1]
 [0 1 1]]


In [3]:
print("Транпонирование: A^T")
A_T = np.transpose(A)
print(A_T)

Транпонирование: A^T
[[1 1 0]
 [0 1 0]
 [0 0 0]]


In [4]:
def invert(matrix):
    return np.subtract(np.ones(shape=matrix.shape), matrix).astype(int)

print("Инвертирование: 1 - A")
bar_A = invert(A)
print(bar_A)

Инвертирование: 1 - A
[[0 1 1]
 [0 0 1]
 [1 1 1]]


In [5]:
print("Вычитание: A - B")
A_sub_B = A & invert(B)
print(A_sub_B)

Вычитание: A - B
[[1 0 0]
 [1 1 0]
 [0 0 0]]


In [6]:
print("Умножение: A x B")
AxB = (A @ B > 0).astype(int)
print(AxB)

Умножение: A x B
[[0 1 0]
 [0 1 1]
 [0 0 0]]
